version: '3'

# Services
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    environment:
    - RABBITMQ_ERLANG_COOKIE=12345
    - RABBITMQ_DEFAULT_USER=guest
    - RABBITMQ_DEFAULT_PASS=guest
    - RABBITMQ_DEFAULT_VHOST=/
    ports:
    - "15672:15672"
    - "5672:5672"
    labels:
      NAME: "rabbitmq"
    networks:
      - routing

  lupakartta_api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    image: lupakartta/api:latest
    command: --config configs/api.edn
    ports:
      - "8080:8080"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
      restart_policy:
        condition: on-failure
    networks:
      - routing
      - microservices

networks:
  microservices:
  routing:
